;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-mini
        indent-for-tab-command
        kill-region
        org-end-of-line
        org-self-insert-command
        sgml-slash
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        find-file
        handle-switch-frame
        js2-mode-show-node
        mac-mwheel-scroll
        markdown-dedent-or-delete
        markdown-exdent-or-delete
        markdown-outdent-or-delete
        mouse-set-region
        ))
