#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

# install oh-my-zsh if it's missing
if [ ! -d ~/.oh-my-zsh ]
then
    echo "Installing Oh My ZSH"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
    echo "Skipping Oh My ZSH install since it's already installed"
fi

if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]
then
    echo "Installing the zsh-syntax-highlighting plugin"
    pushd ~/.oh-my-zsh/custom/plugins
    git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
    popd
    mkdir -p "$HOME/.zfunctions"
    cp "./zsh/pure.zsh" "$HOME/.zfunctions/prompt_pure_setup"
    cp "./zsh/async.zsh" "$HOME/.zfunctions/async"
    cp "./zsh/bullet-train.zsh-theme" "$HOME/.oh-my-zsh/themes"
else
    echo "Skipping zsh-syntax-highlighting plugin because it's already installed"
fi
