name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
